[package]
name = "receipt-shard"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
accensa-common = { workspace = true }
sha2 = { version = "0.10.9", default-features = false }
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
